#!/bin/bash

MEA_BIN=`dirname $0`
source $MEA_BIN/mea.config

function usage {
    echo "
Program: MEA (a Methylomic and Epigenomic Allele-specific analysis pipeline)
Contact: Hamid Younesy <hyounesy@bcgsc.ca> Julien Richard Albert <jrichardalbert@gmail.com>

Usage:   mea <command> [options]

Command:
         phaseVCF       creates phased VCF file from an unphased VCF and
                        haplotypes (.haps)
                        
         createGenome   creates insilico genome (.fasta) from a reference
                        genome and phased variants (.vcf)
                        
         alignReads     aligns reads (.fastq) to the insilico genomes and
                        filters allelic reads
                        
         createTracks   creates bigwig tracks (.bw) from the allelic reads
         
         createReport	creates tab-delimited (.bed) from allelic tracks
         				and user-defined regions of interest
"
}

if test $# -ge 1
then
    VAR_COMMAND=$1
    shift
    
    case $VAR_COMMAND in
        phaseVCF)
            $MEA_BIN/phaseVCF.sh $@
            ;;
            
        createGenome)
            $MEA_BIN/createGenome.sh $@
            ;;

        alignReads)
            $MEA_BIN/alignReads.sh $@
            ;;

        createTracks)
            $MEA_BIN/createTracks.sh $@
            ;;
            
        createReport)
            $MEA_BIN/createReport.sh $@
            ;;
            
        -h )
            usage
            exit 0
            ;;

        * )
            usage
            exit 1
            ;;
    esac
    
    VAR_CODE=$?
    exit $VAR_CODE
fi

usage
exit 1
